version: "3"

name: local-proxy

services:
  nginx:
    image: nginx:1.27-alpine
    container_name: local-proxy_nginx
    restart: always
    volumes:
      - ${HOST_ROOT}/www/local-proxy/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ${HOST_ROOT}/www/local-proxy/nginx/conf.d:/etc/nginx/conf.d
    ports:
      - 80:80
    networks:
      - local-network

networks:
  local-network:
    driver: bridge